behaviors:
    ParkAgent:
        trainer_type: ppo
        hyperparameters:
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
        max_steps: 100000000
        summary_freq: 5000